"""
Django .po formatter.
"""

import re
from typing import Optional, TextIO

from twine.formatters import AbstractFormatter


class DjangoFormatter(AbstractFormatter):
    """Formatter for Django .po files."""

    def __init__(self):
        super().__init__()
        self.default_lang = None

    def format_name(self) -> str:
        return "django"

    def extension(self) -> str:
        return ".po"

    def default_file_name(self) -> str:
        return "strings.po"

    def read(self, io: TextIO, lang: str):
        """Read Django .po file."""
        comment_regex = re.compile(r'^\s*#\. *"?(.*)"?$')
        key_regex = re.compile(r'^msgid *"(.*)"$')
        value_regex = re.compile(r'^msgstr *"(.*)"$', re.MULTILINE)

        key = None
        value = None
        comment = None

        for line in io:
            # Extract comment
            comment_match = comment_regex.match(line)
            if comment_match:
                comment = comment_match.group(1)

            # Extract key (msgid)
            key_match = key_regex.match(line)
            if key_match:
                key = key_match.group(1).replace('\\"', '"')

            # Extract value (msgstr)
            value_match = value_regex.match(line)
            if value_match:
                # Handle multiline strings
                value = value_match.group(1)
                value = re.sub(r'"\n"', "", value)
                value = value.replace('\\"', '"')

            # Process entry when we have both key and value
            if key and value:
                self.set_translation_for_key(key, lang, value)

                if comment and not comment.startswith("--------- "):
                    self.set_comment_for_key(key, comment)

                # Reset for next entry
                key = None
                value = None
                comment = None

    def format_file(self, lang: str) -> Optional[str]:
        """Format file, tracking default language."""
        if self.twine_file.language_codes:
            self.default_lang = self.twine_file.language_codes[0]

        result = super().format_file(lang)
        self.default_lang = None
        return result

    def format_header(self, lang: str) -> str:
        """Generate Django .po file header."""
        return f'''# Django Strings File
# Generated by Twine
# Language: {lang}
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\\n"'''

    def format_section_header(self, section) -> str:
        """Format section header as Django-style comment."""
        return f"# --------- {section.name} --------- #\n"

    def format_definition(self, definition, lang: str) -> Optional[str]:
        """Format definition with base translation comment."""
        parts = []

        # Add comment
        comment = self.format_comment(definition, lang)
        if comment:
            parts.append(comment)

        # Add base translation as comment
        base = self.format_base_translation(definition)
        if base:
            parts.append(base)

        # Add key-value
        kv = self.format_key_value(definition, lang)
        if kv:
            parts.append(kv)

        return "".join(parts) if parts else None

    def format_base_translation(self, definition) -> Optional[str]:
        """Format base translation as comment."""
        if self.default_lang:
            base_translation = definition.translations.get(self.default_lang)
            if base_translation:
                return f'# base translation: "{base_translation}"\n'
        return None

    def key_value_pattern(self) -> str:
        """Return key-value pattern for Django."""
        return 'msgid "%(key)s"\nmsgstr "%(value)s"\n'

    def format_comment(self, definition, lang: str) -> Optional[str]:
        """Format comment."""
        if definition.comment:
            escaped = self.escape_quotes(definition.comment)
            return f"#. {escaped}\n"
        return None

    def format_key(self, key: str) -> str:
        """Format key by escaping quotes."""
        return self.escape_quotes(key)

    def format_value(self, value: str) -> str:
        """Format value by escaping quotes."""
        return self.escape_quotes(value)
