"""
Flash/Flex properties formatter.
"""

import re
from typing import Optional, TextIO

from twine.formatters import AbstractFormatter
from twine.placeholders import (
    convert_placeholders_from_flash_to_twine,
    convert_placeholders_from_twine_to_flash,
)


class FlashFormatter(AbstractFormatter):
    """Formatter for Flash/Flex properties files."""

    def format_name(self) -> str:
        return "flash"

    def extension(self) -> str:
        return ".properties"

    def default_file_name(self) -> str:
        return "resources.properties"

    def set_translation_for_key(self, key: str, lang: str, value: str):
        """Convert Flash placeholders to Twine format."""
        value = convert_placeholders_from_flash_to_twine(value)
        super().set_translation_for_key(key, lang, value)

    def read(self, io: TextIO, lang: str):
        """Read Flash properties file."""
        last_comment = None

        for line in io:
            # Match key=value line (handles escaped characters)
            match = re.match(r'((?:[^"\\]|\\.)+)\s*=\s*((?:[^"\\]|\\.)*)', line)

            if match:
                key = match.group(1)
                value = match.group(2).strip()

                self.set_translation_for_key(key, lang, value)

                if last_comment:
                    self.set_comment_for_key(key, last_comment)
                    last_comment = None

            # Match comment line
            comment_match = re.match(r"# *(.*)", line)
            if comment_match:
                last_comment = comment_match.group(1)
            elif not match:
                last_comment = None

    def format_sections(self, twine_file, lang: str) -> str:
        """Format sections with trailing newline."""
        result = super().format_sections(twine_file, lang)
        return result + "\n" if result else ""

    def format_header(self, lang: str) -> str:
        """Generate Flash properties header."""
        header = "## Flash Strings File\n"
        header += "## Generated by Twine\n"
        header += f"## Language: {lang}"
        return header

    def format_section_header(self, section) -> str:
        """Format section header."""
        return f"## {section.name} ##\n"

    def format_comment(self, definition, lang: str) -> Optional[str]:
        """Format comment."""
        if definition.comment:
            return f"# {definition.comment}\n"
        return None

    def key_value_pattern(self) -> str:
        return "%(key)s=%(value)s"

    def format_value(self, value: str) -> str:
        """Convert Twine placeholders to Flash format."""
        return convert_placeholders_from_twine_to_flash(value)
