"""
Tizen XML formatter.
"""

import html
import re
from typing import Optional, TextIO

from twine.formatters import AbstractFormatter
from twine.placeholders import (
    convert_placeholders_from_android_to_twine,
    convert_placeholders_from_twine_to_android,
)


class TizenFormatter(AbstractFormatter):
    """Formatter for Tizen XML string resources."""

    LANG_CODES = {
        "eng-GB": "en",
        "rus-RU": "ru",
        "fra-FR": "fr",
        "deu-DE": "de",
        "spa-ES": "es",
        "ita-IT": "it",
        "ces-CZ": "cs",
        "pol-PL": "pl",
        "por-PT": "pt",
        "ukr-UA": "uk",
    }

    def format_name(self) -> str:
        return "tizen"

    def extension(self) -> str:
        return ".xml"

    def can_handle_directory(self, path: str) -> bool:
        """Check if directory contains Tizen values folders."""
        import os

        try:
            entries = os.listdir(path)
            return any(item.startswith("values") for item in entries)
        except (OSError, IOError):
            return False

    def default_file_name(self) -> str:
        return "strings.xml"

    def determine_language_given_path(self, path: str) -> Optional[str]:
        """Extract language from Tizen path."""
        from pathlib import Path

        path_parts = Path(path).parts

        for segment in path_parts:
            match = re.match(r"^(.*-.*)\.xml$", segment)
            if match:
                lang = match.group(1)
                return self.LANG_CODES.get(lang)

        return None

    def read(self, io: TextIO, lang: str):
        """Read Tizen XML file."""
        content = io.read()

        resources_match = re.search(
            r"<resources(?:[^>]*)>(.*)</resources>", content, re.DOTALL
        )
        if not resources_match:
            return

        resources_content = resources_match.group(1)

        key = None
        value = None
        comment = None
        current_section = None

        key_regex = re.compile(r'<string name="(\w+)">')
        comment_regex = re.compile(r"<!-- (.*) -->")
        section_regex = re.compile(r"<!-- SECTION: (.*) -->")
        value_regex = re.compile(r'<string name="\w+">(.*)</string>')

        for line in resources_content.split("\n"):
            # Check for key
            key_match = key_regex.search(line)
            if key_match:
                key = key_match.group(1)

                # Check for value on same line
                value_match = value_regex.search(line)
                if value_match:
                    value = value_match.group(1)
                    # Unescape
                    value = html.unescape(value)
                    value = value.replace("\\'", "'")
                    value = value.replace('\\"', '"')
                    value = convert_placeholders_from_android_to_twine(value)

                    # Convert \u0020 space escapes
                    def replace_spaces(match):
                        spaces = match.group(0)
                        return " " * (len(spaces) // 6)

                    value = re.sub(r"(\\u0020)+", replace_spaces, value)
                else:
                    value = ""

                self.set_translation_for_key(key, lang, value, current_section)

                if comment and not comment.startswith("SECTION:"):
                    self.set_comment_for_key(key, comment)

                comment = None

            # Check for comment
            comment_match = comment_regex.search(line)
            if comment_match:
                comment = comment_match.group(1)

            # Check for section start
            section_match = section_regex.search(line)
            if section_match:
                current_section = section_match.group(1)
                comment = None

    def format_header(self, lang: str) -> str:
        """Generate Tizen XML header."""
        header = '<?xml version="1.0" encoding="utf-8"?>\n'
        header += "<!-- Tizen Strings File -->\n"
        header += "<!-- Generated by Twine -->\n"
        header += f"<!-- Language: {lang} -->"
        return header

    def format_sections(self, twine_file, lang: str) -> str:
        """Format sections with Tizen string_table wrapper."""
        result = '<string_table Bversion="2.0.0.201311071819" Dversion="20120315">'

        sections_content = super().format_sections(twine_file, lang)
        if sections_content:
            result += "\n" + sections_content + "\n"

        result += "</string_table>\n"
        return result

    def format_section_header(self, section) -> str:
        """Format section header as comment."""
        return f"\t<!-- SECTION: {section.name} -->"

    def format_comment(self, definition, lang: str) -> Optional[str]:
        """Format comment, replacing -- with em dash."""
        if definition.comment:
            comment = definition.comment.replace("--", "—")
            return f"\t<!-- {comment} -->\n"
        return None

    def key_value_pattern(self) -> str:
        return '\t<text id="IDS_%(key)s">%(value)s</text>'

    def format_key(self, key: str) -> str:
        """Format key in uppercase."""
        return key.upper()

    def format_value(self, value: str) -> str:
        """Format value with Tizen-specific escaping."""
        # Escape quotes
        value = self.escape_quotes(value)

        # Escape apostrophes
        value = value.replace("'", "\\'")

        # HTML escape
        value = html.escape(value)

        # Convert placeholders
        value = convert_placeholders_from_twine_to_android(value)

        # Replace beginning and end spaces with \u0020
        value = re.sub(r"^ +| +$", lambda m: "\\u0020" * len(m.group(0)), value)

        return value
